FROM node:20.5-alpine3.18 as build-stage
WORKDIR /usr/app
COPY . .
RUN npm i
RUN npm run build

FROM nginx:1.25.2-alpine as production-stage
COPY --from=build-stage /usr/app/dist /usr/share/nginx/html
COPY .docker/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]